(()=>{'use strict';
const $=s=>document.querySelector(s),canvas=$('#game'),ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;
const W=320,H=224,keys=new Set(),info={snake:{name:'SNAKE GARDEN / 贪吃蛇',label:'SNAKE GARDEN',note:'方向键改变方向，吃到果实得分。不要撞到自己或围墙。',action:'加速',color:'#a8bfa4'},race:{name:'POCKET RALLY / 口袋赛车',label:'POCKET RALLY',note:'左右移动躲避车辆，按住空格加速，挑战更远距离。',action:'加速',color:'#d6a282'},breakout:{name:'BRICK BREAKER / 打砖块',label:'BRICK BREAKER',note:'左右移动挡板，空格发球。清空砖块即可过关。',action:'发球',color:'#b5a8cc'},space:{name:'STAR PATROL / 星际巡航',label:'STAR PATROL',note:'方向键驾驶飞船，按住空格射击。击落敌机赢取分数。',action:'射击',color:'#a2b8c1'}};
let active=null,mode='idle',state={},score=0,best={},last=0,acc=0,loadToken=0,sound=false,audio=null;
try{best=JSON.parse(localStorage.getItem('pocket-room-best')||'{}')}catch{}if(!best||typeof best!=='object')best={};
function beep(freq=440,len=.06){if(!sound)return;try{audio||=new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='square';o.frequency.value=freq;g.gain.setValueAtTime(.025,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+len);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+len)}catch{}}
function rect(x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(Math.round(x),Math.round(y),w,h)}
function text(t,x,y,size=10,c='#c4d9bd',align='left'){ctx.fillStyle=c;ctx.font=`bold ${size}px monospace`;ctx.textAlign=align;ctx.fillText(t,x,y)}
function rand(n){return Math.floor(Math.random()*n)}
function init(){score=0;acc=0;keys.clear();if(active==='snake'){state={body:[{x:9,y:8},{x:8,y:8},{x:7,y:8}],dir:{x:1,y:0},next:{x:1,y:0},food:{x:16,y:8},tick:0}}if(active==='race')state={x:153,enemies:[],spawn:0,road:0,distance:0};if(active==='breakout')state={x:132,ball:{x:160,y:191,vx:90,vy:-110},launched:false,lives:3,bricks:Array.from({length:40},(_,i)=>({x:17+i%8*36,y:40+Math.floor(i/8)*14,alive:true}))};if(active==='space')state={x:150,y:183,shots:[],enemies:[],spawn:0,shoot:0,lives:3,inv:0};}
function finish(win=false){mode=win?'win':'over';if(score>(Number(best[active])||0)){best[active]=score;try{localStorage.setItem('pocket-room-best',JSON.stringify(best))}catch{}}beep(win?880:110,.25)}
function start(){if(!active||mode==='loading')return;if(mode==='ready'||mode==='over'||mode==='win'){init();mode='playing';beep(660)}else if(mode==='playing'){mode='paused'}else if(mode==='paused'){mode='playing';last=performance.now()}}
function select(id){if(mode==='loading'||!info[id])return;active=id;mode='loading';keys.clear();const token=++loadToken;$('#inserted').classList.remove('loaded');document.querySelectorAll('.cartridge').forEach(e=>{e.classList.toggle('active',e.dataset.game===id);e.setAttribute('aria-pressed',e.dataset.game===id?'true':'false')});$('#now-playing').textContent='正在插入卡带…';$('#game-note').textContent=info[id].note;$('#action-label').textContent=info[id].action;$('#eject').disabled=false;setTimeout(()=>{if(token!==loadToken)return;$('#insert-label').textContent=info[id].label;$('#insert-label').style.background=info[id].color;$('#inserted').classList.add('loaded');beep(330)},180);setTimeout(()=>{if(token!==loadToken)return;init();mode='ready';$('#now-playing').textContent=info[id].name;beep(660)},850)}
function eject(){++loadToken;active=null;mode='idle';keys.clear();$('#inserted').classList.remove('loaded');document.querySelectorAll('.cartridge').forEach(e=>{e.classList.remove('active');e.setAttribute('aria-pressed','false')});$('#now-playing').textContent='等待插入卡带';$('#game-note').textContent='你的下一场冒险，由你选择。';$('#action-label').textContent='动作';$('#eject').disabled=true;beep(220)}
function direction(k){if(active!=='snake'||mode!=='playing')return;const d={ArrowUp:{x:0,y:-1},ArrowDown:{x:0,y:1},ArrowLeft:{x:-1,y:0},ArrowRight:{x:1,y:0}}[k];if(d&&(d.x!==-state.dir.x||d.y!==-state.dir.y))state.next=d}
function keydown(k,repeat=false){if(window.gbaPlayer?.active)return;keys.add(k);if(k==='Enter'&&!repeat)start();if(k==='Escape'&&mode==='playing')mode='paused';direction(k);if((k===' '||k==='z')&&!repeat){if(['ready','over','win'].includes(mode))start();else if(active==='breakout'&&mode==='playing')state.launched=true}document.querySelectorAll('[data-key]').forEach(b=>b.classList.toggle('pressed',keys.has(b.dataset.key)))}
function keyup(k){keys.delete(k);document.querySelectorAll('[data-key]').forEach(b=>b.classList.toggle('pressed',keys.has(b.dataset.key)))}
const alias={w:'ArrowUp',a:'ArrowLeft',s:'ArrowDown',d:'ArrowRight',W:'ArrowUp',A:'ArrowLeft',S:'ArrowDown',D:'ArrowRight'};
window.addEventListener('keydown',e=>{if(window.gbaPlayer?.active)return;const k=alias[e.key]||e.key;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' ','Enter','Escape','z'].includes(k)){if(e.target instanceof HTMLButtonElement&&['Enter',' '].includes(k))return;e.preventDefault();keydown(k,e.repeat)}});window.addEventListener('keyup',e=>keyup(alias[e.key]||e.key));window.addEventListener('blur',()=>{keys.clear();document.querySelectorAll('.pressed').forEach(e=>e.classList.remove('pressed'));if(mode==='playing')mode='paused'});document.addEventListener('visibilitychange',()=>{if(document.hidden&&mode==='playing'){mode='paused';keys.clear()}});
document.querySelectorAll('.cartridge').forEach(b=>b.addEventListener('click',()=>{select(b.dataset.game);b.blur()}));document.querySelectorAll('[data-key]').forEach(b=>{b.style.touchAction='none';b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keydown(b.dataset.key)});b.addEventListener('pointerup',()=>keyup(b.dataset.key));b.addEventListener('pointercancel',()=>keyup(b.dataset.key));b.addEventListener('click',e=>{if(e.detail===0){keydown(b.dataset.key);keyup(b.dataset.key)}})});$('#start').onclick=()=>{start();$('#start').blur()};$('#select').onclick=eject;$('#eject').onclick=eject;$('#sound').onclick=()=>{sound=!sound;$('#sound').textContent='声音 '+(sound?'ON':'OFF');$('#sound').setAttribute('aria-label',sound?'关闭音效':'开启音效');$('#sound').setAttribute('aria-pressed',String(sound));beep();$('#sound').blur()};
function overlap(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}
function update(dt){if(mode!=='playing')return;const left=keys.has('ArrowLeft'),right=keys.has('ArrowRight'),fire=keys.has(' ')||keys.has('z');
if(active==='snake'){state.tick+=dt;if(state.tick<(fire?.065:.145))return;state.tick=0;state.dir=state.next;const h={x:state.body[0].x+state.dir.x,y:state.body[0].y+state.dir.y},eats=h.x===state.food.x&&h.y===state.food.y;if(h.x<0||h.x>=24||h.y<0||h.y>=14||state.body.slice(0,eats?undefined:-1).some(p=>p.x===h.x&&p.y===h.y)){finish();return}state.body.unshift(h);if(eats){score+=10;beep(740);if(state.body.length===336){finish(true);return}do{state.food={x:rand(24),y:rand(14)}}while(state.body.some(p=>p.x===state.food.x&&p.y===state.food.y))}else state.body.pop();}
if(active==='race'){state.x=Math.max(76,Math.min(226,state.x+(right-left)*165*dt));const speed=fire?205:115;state.road=(state.road+speed*dt)%38;state.distance+=speed*dt;score=Math.floor(state.distance/30);state.spawn-=dt;if(state.spawn<=0){state.enemies.push({x:85+rand(3)*55,y:-30,w:19,h:31});state.spawn=Math.max(.5,1.1-score*.002)}for(const e of state.enemies){e.y+=(speed+score*.3)*dt;if(overlap({x:state.x+2,y:174,w:15,h:28},e)){finish();return}}state.enemies=state.enemies.filter(e=>e.y<240)}
if(active==='breakout'){state.x=Math.max(7,Math.min(261,state.x+(right-left)*210*dt));let b=state.ball;if(!state.launched){b.x=state.x+26;b.y=191;return}b.x+=b.vx*dt;b.y+=b.vy*dt;if(b.x<9){b.x=9;b.vx=Math.abs(b.vx)}if(b.x>311){b.x=311;b.vx=-Math.abs(b.vx)}if(b.y<28){b.y=28;b.vy=Math.abs(b.vy)}if(b.vy>0&&b.y>=192&&b.y<=203&&b.x>=state.x-3&&b.x<=state.x+55){b.y=191;b.vy=-Math.abs(b.vy);b.vx=(b.x-state.x-26)*5;beep(400)}for(const brick of state.bricks){if(brick.alive&&overlap({x:b.x-3,y:b.y-3,w:6,h:6},{x:brick.x,y:brick.y,w:32,h:10})){brick.alive=false;b.vy=-b.vy;score+=10;beep(650);break}}if(b.y>H+5){state.lives--;if(!state.lives){finish();return}state.launched=false;b.vx=90;b.vy=-110}if(state.bricks.every(e=>!e.alive))finish(true)}
if(active==='space'){state.x=Math.max(7,Math.min(297,state.x+(right-left)*170*dt));state.y=Math.max(40,Math.min(203,state.y+((keys.has('ArrowDown')?1:0)-(keys.has('ArrowUp')?1:0))*150*dt));state.shoot-=dt;state.spawn-=dt;state.inv-=dt;if(fire&&state.shoot<=0){state.shots.push({x:state.x+7,y:state.y,w:3,h:8});state.shoot=.17;beep(880,.025)}if(state.spawn<=0){state.enemies.push({x:12+rand(280),y:15,w:17,h:15});state.spawn=Math.max(.22,.8-score/1500)}state.shots.forEach(s=>s.y-=270*dt);for(const e of state.enemies){e.y+=(40+score/15)*dt;for(const s of state.shots){if(!e.dead&&!s.dead&&overlap(e,s)){e.dead=true;s.dead=true;score+=20;beep(220)}}if(!e.dead&&(e.y>224||overlap({x:state.x+3,y:state.y+3,w:11,h:14},e))){e.dead=true;if(state.inv<=0){state.lives--;state.inv=.9;beep(100,.15);if(state.lives<=0){finish();return}}}}state.shots=state.shots.filter(s=>s.y>20&&!s.dead);state.enemies=state.enemies.filter(e=>!e.dead)}
}
function car(x,y,c){rect(x+2,y,15,31,c);rect(x+4,y+5,11,8,'#28363a');rect(x+4,y+22,11,5,'#28363a');rect(x,y+6,3,7,'#182323');rect(x+16,y+6,3,7,'#182323');rect(x,y+22,3,7,'#182323');rect(x+16,y+22,3,7,'#182323');rect(x+3,y+1,3,2,'#ecdeb3');rect(x+13,y+1,3,2,'#ecdeb3')}
function ship(x,y,c,flip=false){const py=flip?y+13:y;rect(x+7,py,3,4,c);rect(x+4,y+4,9,10,c);rect(x,y+9,17,5,c);rect(x+7,y+6,3,5,'#263748');if(!flip){rect(x+3,y+15,3,3,'#dca066');rect(x+11,y+15,3,3,'#dca066')}}
function draw(t){rect(0,0,W,H,'#1c2b2a');if(mode==='idle'||mode==='loading'){for(let x=0;x<W;x+=16)for(let y=0;y<H;y+=16)rect(x,y,1,1,'#34433e');text('P O C K E T',160,69,22,'#c9d6bd','center');text('R O O M',160,93,16,'#9faa9b','center');rect(140,116,40,28,'#9aa889');rect(144,120,32,14,'#253b33');rect(147,138,8,2,'#344b3d');rect(171,137,3,3,'#344b3d');text(mode==='loading'?'READING CARTRIDGE...':'INSERT A CARTRIDGE',160,167,10,'#c7d5b6','center');text('A LITTLE JOY. PRESS PLAY.',160,198,7,'#728779','center');return}
if(active==='snake'){rect(13,34,294,173,'#283e32');for(let x=0;x<24;x++)for(let y=0;y<14;y++)rect(16+x*12,37+y*12,11,11,'#2e4437');state.body.forEach((p,i)=>rect(16+p.x*12,37+p.y*12,11,11,i?'#a3bc7e':'#d4df9f'));let h=state.body[0];rect(19+h.x*12,39+h.y*12,2,2,'#344b3d');rect(23+h.x*12,39+h.y*12,2,2,'#344b3d');rect(18+state.food.x*12,39+state.food.y*12,7,8,'#d48e74');rect(22+state.food.x*12,37+state.food.y*12,2,3,'#c2ce8d')}
if(active==='race'){rect(0,25,320,199,'#84977b');rect(70,25,180,199,'#394447');for(let i=-1;i<7;i++){const y=i*38+state.road;rect(67,y,4,20,'#d2c4aa');rect(250,y,4,20,'#d2c4aa');rect(126,y,2,20,'#bdb7a2');rect(184,y,2,20,'#bdb7a2')}car(state.x,174,'#deb08e');state.enemies.forEach(e=>car(e.x,e.y,'#a3b7c4'))}
if(active==='breakout'){rect(0,25,W,199,'#252b3a');state.bricks.forEach((b,i)=>{if(b.alive){rect(b.x,b.y,32,10,['#b59dbf','#cda2a0','#d9bd8d','#a3b79a','#95b3ba'][Math.floor(i/8)]);rect(b.x,b.y,32,2,'#ffffff25')}});rect(state.x,197,52,6,'#bba7d4');rect(state.ball.x-3,state.ball.y-3,6,6,'#eee1bc');text('LIFE '+state.lives,12,217,7,'#a2a5b4');if(!state.launched&&mode==='playing')text('SPACE TO LAUNCH',160,150,9,'#cbbcdc','center')}
if(active==='space'){rect(0,25,W,199,'#202c3b');for(let i=0;i<42;i++)rect((i*73)%320,28+((i*39+t*.025)%194),i%5===0?2:1,2,'#657887');state.shots.forEach(s=>rect(s.x,s.y,3,8,'#e9d49d'));state.enemies.forEach(e=>ship(e.x,e.y,'#c99498',true));if(state.inv<=0||Math.floor(t/80)%2===0)ship(state.x,state.y,'#a4c9cb');text('SHIELDS '+state.lives,12,217,7,'#a5bfc4')}
rect(0,0,320,25,'#192725');text('SCORE '+String(score).padStart(4,'0'),10,16,9);text('BEST '+String(Math.max(score,Number(best[active])||0)).padStart(4,'0'),310,16,9,'#9bad96','right');
if(mode!=='playing'){rect(33,70,254,94,'#142220e8');let title=mode==='ready'?info[active].label:mode==='paused'?'PAUSED':mode==='win'?'YOU WIN!':'GAME OVER';text(title,160,103,17,info[active].color,'center');text(mode==='over'||mode==='win'?'SCORE '+score:'READY FOR A LITTLE FUN?',160,123,9,'#c6cfbc','center');text(mode==='paused'?'ENTER TO RESUME':'PRESS ENTER TO PLAY',160,146,9,'#b6c4aa','center')}
}
function loop(t){let dt=Math.min((t-last)/1000,.05);last=t;acc+=dt;while(acc>=1/120){update(1/120);acc-=1/120}draw(t);requestAnimationFrame(loop)}requestAnimationFrame(loop);
window.pocketRoom={eject,getSnapshot:()=>({active,mode,score,state:JSON.parse(JSON.stringify(state))})};
})();
